const colors = {
  light: {
    text: '#545454',
    tint: '#002d3e',
    background: '#fdfaf6',
    foreground: '#0a0a0a',
    card: '#ffffff',
    cardForeground: '#0a0a0a',
    primary: '#002d3e',
    primaryForeground: '#ffffff',
    secondary: '#f0f0f0',
    secondaryForeground: '#1a1a1a',
    muted: '#f0f0f0',
    mutedForeground: '#737373',
    accent: '#f2690d',
    accentForeground: '#ffffff',
    destructive: '#ef4444',
    destructiveForeground: '#ffffff',
    border: '#e6e4e0',
    input: '#e6e4e0',
  },
  dark: {
    text: '#ececec',
    tint: '#004866',
    background: '#0a0a0a',
    foreground: '#ffffff',
    card: '#1a1a1a',
    cardForeground: '#ffffff',
    primary: '#004866',
    primaryForeground: '#ffffff',
    secondary: '#333333',
    secondaryForeground: '#ececec',
    muted: '#2a2a2a',
    mutedForeground: '#a3a3a3',
    accent: '#f2690d',
    accentForeground: '#ffffff',
    destructive: '#ef4444',
    destructiveForeground: '#ffffff',
    border: '#333333',
    input: '#333333',
  },
  radius: 8,
};

export default colors;